/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUnidadesRouteImport } from './routes/_authenticated/unidades'
import { Route as AuthenticatedSimuladorCaixaRouteImport } from './routes/_authenticated/simulador-caixa'
import { Route as AuthenticatedRoyaltiesRouteImport } from './routes/_authenticated/royalties'
import { Route as AuthenticatedReformaTributariaRouteImport } from './routes/_authenticated/reforma-tributaria'
import { Route as AuthenticatedRedeRealizadoRouteImport } from './routes/_authenticated/rede-realizado'
import { Route as AuthenticatedRedeOverviewRouteImport } from './routes/_authenticated/rede-overview'
import { Route as AuthenticatedRedeLtvRouteImport } from './routes/_authenticated/rede-ltv'
import { Route as AuthenticatedRedeHeadcountRouteImport } from './routes/_authenticated/rede-headcount'
import { Route as AuthenticatedRedeRouteImport } from './routes/_authenticated/rede'
import { Route as AuthenticatedReconciliacaoRouteImport } from './routes/_authenticated/reconciliacao'
import { Route as AuthenticatedPainelUnidadeRouteImport } from './routes/_authenticated/painel-unidade'
import { Route as AuthenticatedPainelCsRouteImport } from './routes/_authenticated/painel-cs'
import { Route as AuthenticatedPagamentosUnidadesRouteImport } from './routes/_authenticated/pagamentos-unidades'
import { Route as AuthenticatedOperacaoRouteImport } from './routes/_authenticated/operacao'
import { Route as AuthenticatedNpsRouteImport } from './routes/_authenticated/nps'
import { Route as AuthenticatedMeusRoyaltiesRouteImport } from './routes/_authenticated/meus-royalties'
import { Route as AuthenticatedIndicadoresTrimestreRouteImport } from './routes/_authenticated/indicadores-trimestre'
import { Route as AuthenticatedFunilReceitaRouteImport } from './routes/_authenticated/funil-receita'
import { Route as AuthenticatedFinanceiroPartnersRouteImport } from './routes/_authenticated/financeiro-partners'
import { Route as AuthenticatedFilaCellaRouteImport } from './routes/_authenticated/fila-cella'
import { Route as AuthenticatedEbitOperacionalRouteImport } from './routes/_authenticated/ebit-operacional'
import { Route as AuthenticatedDrePartnersRouteImport } from './routes/_authenticated/dre-partners'
import { Route as AuthenticatedDisparosWhatsappRouteImport } from './routes/_authenticated/disparos-whatsapp'
import { Route as AuthenticatedDespesasCmRouteImport } from './routes/_authenticated/despesas-cm'
import { Route as AuthenticatedContasReceberRouteImport } from './routes/_authenticated/contas-receber'
import { Route as AuthenticatedComissoesRouteImport } from './routes/_authenticated/comissoes'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedBiVendasRouteImport } from './routes/_authenticated/bi-vendas'
import { Route as AuthenticatedBaseContatosRouteImport } from './routes/_authenticated/base-contatos'
import { Route as AuthenticatedAuditoriaInternaRouteImport } from './routes/_authenticated/auditoria-interna'
import { Route as AuthenticatedAuditoriaFaturamentoRouteImport } from './routes/_authenticated/auditoria-faturamento'
import { Route as AuthenticatedAuditoriaRouteImport } from './routes/_authenticated/auditoria'
import { Route as AuthenticatedAtividadeRouteImport } from './routes/_authenticated/atividade'
import { Route as AuthenticatedRoyaltiesIndexRouteImport } from './routes/_authenticated/royalties.index'
import { Route as AuthenticatedBrokerIndexRouteImport } from './routes/_authenticated/broker.index'
import { Route as AuthenticatedBrokerAdminRouteImport } from './routes/_authenticated/broker.admin'
import { Route as AuthenticatedAdminValidacaoRouteImport } from './routes/_authenticated/admin.validacao'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedAdminPermissoesRouteImport } from './routes/_authenticated/admin.permissoes'
import { Route as AuthenticatedAdminPerfisRouteImport } from './routes/_authenticated/admin.perfis'
import { Route as AuthenticatedAdminIntegracoesRouteImport } from './routes/_authenticated/admin.integracoes'
import { Route as AuthenticatedRoyaltiesUnidadeIdMesRouteImport } from './routes/_authenticated/royalties.$unidadeId.$mes'

const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUnidadesRoute = AuthenticatedUnidadesRouteImport.update({
  id: '/unidades',
  path: '/unidades',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSimuladorCaixaRoute =
  AuthenticatedSimuladorCaixaRouteImport.update({
    id: '/simulador-caixa',
    path: '/simulador-caixa',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRoyaltiesRoute = AuthenticatedRoyaltiesRouteImport.update({
  id: '/royalties',
  path: '/royalties',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReformaTributariaRoute =
  AuthenticatedReformaTributariaRouteImport.update({
    id: '/reforma-tributaria',
    path: '/reforma-tributaria',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRedeRealizadoRoute =
  AuthenticatedRedeRealizadoRouteImport.update({
    id: '/rede-realizado',
    path: '/rede-realizado',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRedeOverviewRoute =
  AuthenticatedRedeOverviewRouteImport.update({
    id: '/rede-overview',
    path: '/rede-overview',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRedeLtvRoute = AuthenticatedRedeLtvRouteImport.update({
  id: '/rede-ltv',
  path: '/rede-ltv',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRedeHeadcountRoute =
  AuthenticatedRedeHeadcountRouteImport.update({
    id: '/rede-headcount',
    path: '/rede-headcount',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRedeRoute = AuthenticatedRedeRouteImport.update({
  id: '/rede',
  path: '/rede',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReconciliacaoRoute =
  AuthenticatedReconciliacaoRouteImport.update({
    id: '/reconciliacao',
    path: '/reconciliacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelUnidadeRoute =
  AuthenticatedPainelUnidadeRouteImport.update({
    id: '/painel-unidade',
    path: '/painel-unidade',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelCsRoute = AuthenticatedPainelCsRouteImport.update({
  id: '/painel-cs',
  path: '/painel-cs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPagamentosUnidadesRoute =
  AuthenticatedPagamentosUnidadesRouteImport.update({
    id: '/pagamentos-unidades',
    path: '/pagamentos-unidades',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperacaoRoute = AuthenticatedOperacaoRouteImport.update({
  id: '/operacao',
  path: '/operacao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNpsRoute = AuthenticatedNpsRouteImport.update({
  id: '/nps',
  path: '/nps',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeusRoyaltiesRoute =
  AuthenticatedMeusRoyaltiesRouteImport.update({
    id: '/meus-royalties',
    path: '/meus-royalties',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIndicadoresTrimestreRoute =
  AuthenticatedIndicadoresTrimestreRouteImport.update({
    id: '/indicadores-trimestre',
    path: '/indicadores-trimestre',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFunilReceitaRoute =
  AuthenticatedFunilReceitaRouteImport.update({
    id: '/funil-receita',
    path: '/funil-receita',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroPartnersRoute =
  AuthenticatedFinanceiroPartnersRouteImport.update({
    id: '/financeiro-partners',
    path: '/financeiro-partners',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFilaCellaRoute = AuthenticatedFilaCellaRouteImport.update({
  id: '/fila-cella',
  path: '/fila-cella',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEbitOperacionalRoute =
  AuthenticatedEbitOperacionalRouteImport.update({
    id: '/ebit-operacional',
    path: '/ebit-operacional',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDrePartnersRoute =
  AuthenticatedDrePartnersRouteImport.update({
    id: '/dre-partners',
    path: '/dre-partners',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDisparosWhatsappRoute =
  AuthenticatedDisparosWhatsappRouteImport.update({
    id: '/disparos-whatsapp',
    path: '/disparos-whatsapp',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDespesasCmRoute = AuthenticatedDespesasCmRouteImport.update({
  id: '/despesas-cm',
  path: '/despesas-cm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContasReceberRoute =
  AuthenticatedContasReceberRouteImport.update({
    id: '/contas-receber',
    path: '/contas-receber',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComissoesRoute = AuthenticatedComissoesRouteImport.update({
  id: '/comissoes',
  path: '/comissoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBiVendasRoute = AuthenticatedBiVendasRouteImport.update({
  id: '/bi-vendas',
  path: '/bi-vendas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBaseContatosRoute =
  AuthenticatedBaseContatosRouteImport.update({
    id: '/base-contatos',
    path: '/base-contatos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditoriaInternaRoute =
  AuthenticatedAuditoriaInternaRouteImport.update({
    id: '/auditoria-interna',
    path: '/auditoria-interna',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditoriaFaturamentoRoute =
  AuthenticatedAuditoriaFaturamentoRouteImport.update({
    id: '/auditoria-faturamento',
    path: '/auditoria-faturamento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditoriaRoute = AuthenticatedAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAtividadeRoute = AuthenticatedAtividadeRouteImport.update({
  id: '/atividade',
  path: '/atividade',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoyaltiesIndexRoute =
  AuthenticatedRoyaltiesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRoyaltiesRoute,
  } as any)
const AuthenticatedBrokerIndexRoute =
  AuthenticatedBrokerIndexRouteImport.update({
    id: '/broker/',
    path: '/broker/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBrokerAdminRoute =
  AuthenticatedBrokerAdminRouteImport.update({
    id: '/broker/admin',
    path: '/broker/admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminValidacaoRoute =
  AuthenticatedAdminValidacaoRouteImport.update({
    id: '/admin/validacao',
    path: '/admin/validacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPermissoesRoute =
  AuthenticatedAdminPermissoesRouteImport.update({
    id: '/admin/permissoes',
    path: '/admin/permissoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPerfisRoute =
  AuthenticatedAdminPerfisRouteImport.update({
    id: '/admin/perfis',
    path: '/admin/perfis',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIntegracoesRoute =
  AuthenticatedAdminIntegracoesRouteImport.update({
    id: '/admin/integracoes',
    path: '/admin/integracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRoyaltiesUnidadeIdMesRoute =
  AuthenticatedRoyaltiesUnidadeIdMesRouteImport.update({
    id: '/$unidadeId/$mes',
    path: '/$unidadeId/$mes',
    getParentRoute: () => AuthenticatedRoyaltiesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/trust': typeof TrustRoute
  '/atividade': typeof AuthenticatedAtividadeRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/auditoria-faturamento': typeof AuthenticatedAuditoriaFaturamentoRoute
  '/auditoria-interna': typeof AuthenticatedAuditoriaInternaRoute
  '/base-contatos': typeof AuthenticatedBaseContatosRoute
  '/bi-vendas': typeof AuthenticatedBiVendasRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/comissoes': typeof AuthenticatedComissoesRoute
  '/contas-receber': typeof AuthenticatedContasReceberRoute
  '/despesas-cm': typeof AuthenticatedDespesasCmRoute
  '/disparos-whatsapp': typeof AuthenticatedDisparosWhatsappRoute
  '/dre-partners': typeof AuthenticatedDrePartnersRoute
  '/ebit-operacional': typeof AuthenticatedEbitOperacionalRoute
  '/fila-cella': typeof AuthenticatedFilaCellaRoute
  '/financeiro-partners': typeof AuthenticatedFinanceiroPartnersRoute
  '/funil-receita': typeof AuthenticatedFunilReceitaRoute
  '/indicadores-trimestre': typeof AuthenticatedIndicadoresTrimestreRoute
  '/meus-royalties': typeof AuthenticatedMeusRoyaltiesRoute
  '/nps': typeof AuthenticatedNpsRoute
  '/operacao': typeof AuthenticatedOperacaoRoute
  '/pagamentos-unidades': typeof AuthenticatedPagamentosUnidadesRoute
  '/painel-cs': typeof AuthenticatedPainelCsRoute
  '/painel-unidade': typeof AuthenticatedPainelUnidadeRoute
  '/reconciliacao': typeof AuthenticatedReconciliacaoRoute
  '/rede': typeof AuthenticatedRedeRoute
  '/rede-headcount': typeof AuthenticatedRedeHeadcountRoute
  '/rede-ltv': typeof AuthenticatedRedeLtvRoute
  '/rede-overview': typeof AuthenticatedRedeOverviewRoute
  '/rede-realizado': typeof AuthenticatedRedeRealizadoRoute
  '/reforma-tributaria': typeof AuthenticatedReformaTributariaRoute
  '/royalties': typeof AuthenticatedRoyaltiesRouteWithChildren
  '/simulador-caixa': typeof AuthenticatedSimuladorCaixaRoute
  '/unidades': typeof AuthenticatedUnidadesRoute
  '/admin/integracoes': typeof AuthenticatedAdminIntegracoesRoute
  '/admin/perfis': typeof AuthenticatedAdminPerfisRoute
  '/admin/permissoes': typeof AuthenticatedAdminPermissoesRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/validacao': typeof AuthenticatedAdminValidacaoRoute
  '/broker/admin': typeof AuthenticatedBrokerAdminRoute
  '/broker/': typeof AuthenticatedBrokerIndexRoute
  '/royalties/': typeof AuthenticatedRoyaltiesIndexRoute
  '/royalties/$unidadeId/$mes': typeof AuthenticatedRoyaltiesUnidadeIdMesRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/trust': typeof TrustRoute
  '/atividade': typeof AuthenticatedAtividadeRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/auditoria-faturamento': typeof AuthenticatedAuditoriaFaturamentoRoute
  '/auditoria-interna': typeof AuthenticatedAuditoriaInternaRoute
  '/base-contatos': typeof AuthenticatedBaseContatosRoute
  '/bi-vendas': typeof AuthenticatedBiVendasRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/comissoes': typeof AuthenticatedComissoesRoute
  '/contas-receber': typeof AuthenticatedContasReceberRoute
  '/despesas-cm': typeof AuthenticatedDespesasCmRoute
  '/disparos-whatsapp': typeof AuthenticatedDisparosWhatsappRoute
  '/dre-partners': typeof AuthenticatedDrePartnersRoute
  '/ebit-operacional': typeof AuthenticatedEbitOperacionalRoute
  '/fila-cella': typeof AuthenticatedFilaCellaRoute
  '/financeiro-partners': typeof AuthenticatedFinanceiroPartnersRoute
  '/funil-receita': typeof AuthenticatedFunilReceitaRoute
  '/indicadores-trimestre': typeof AuthenticatedIndicadoresTrimestreRoute
  '/meus-royalties': typeof AuthenticatedMeusRoyaltiesRoute
  '/nps': typeof AuthenticatedNpsRoute
  '/operacao': typeof AuthenticatedOperacaoRoute
  '/pagamentos-unidades': typeof AuthenticatedPagamentosUnidadesRoute
  '/painel-cs': typeof AuthenticatedPainelCsRoute
  '/painel-unidade': typeof AuthenticatedPainelUnidadeRoute
  '/reconciliacao': typeof AuthenticatedReconciliacaoRoute
  '/rede': typeof AuthenticatedRedeRoute
  '/rede-headcount': typeof AuthenticatedRedeHeadcountRoute
  '/rede-ltv': typeof AuthenticatedRedeLtvRoute
  '/rede-overview': typeof AuthenticatedRedeOverviewRoute
  '/rede-realizado': typeof AuthenticatedRedeRealizadoRoute
  '/reforma-tributaria': typeof AuthenticatedReformaTributariaRoute
  '/simulador-caixa': typeof AuthenticatedSimuladorCaixaRoute
  '/unidades': typeof AuthenticatedUnidadesRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/integracoes': typeof AuthenticatedAdminIntegracoesRoute
  '/admin/perfis': typeof AuthenticatedAdminPerfisRoute
  '/admin/permissoes': typeof AuthenticatedAdminPermissoesRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/validacao': typeof AuthenticatedAdminValidacaoRoute
  '/broker/admin': typeof AuthenticatedBrokerAdminRoute
  '/broker': typeof AuthenticatedBrokerIndexRoute
  '/royalties': typeof AuthenticatedRoyaltiesIndexRoute
  '/royalties/$unidadeId/$mes': typeof AuthenticatedRoyaltiesUnidadeIdMesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/trust': typeof TrustRoute
  '/_authenticated/atividade': typeof AuthenticatedAtividadeRoute
  '/_authenticated/auditoria': typeof AuthenticatedAuditoriaRoute
  '/_authenticated/auditoria-faturamento': typeof AuthenticatedAuditoriaFaturamentoRoute
  '/_authenticated/auditoria-interna': typeof AuthenticatedAuditoriaInternaRoute
  '/_authenticated/base-contatos': typeof AuthenticatedBaseContatosRoute
  '/_authenticated/bi-vendas': typeof AuthenticatedBiVendasRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/comissoes': typeof AuthenticatedComissoesRoute
  '/_authenticated/contas-receber': typeof AuthenticatedContasReceberRoute
  '/_authenticated/despesas-cm': typeof AuthenticatedDespesasCmRoute
  '/_authenticated/disparos-whatsapp': typeof AuthenticatedDisparosWhatsappRoute
  '/_authenticated/dre-partners': typeof AuthenticatedDrePartnersRoute
  '/_authenticated/ebit-operacional': typeof AuthenticatedEbitOperacionalRoute
  '/_authenticated/fila-cella': typeof AuthenticatedFilaCellaRoute
  '/_authenticated/financeiro-partners': typeof AuthenticatedFinanceiroPartnersRoute
  '/_authenticated/funil-receita': typeof AuthenticatedFunilReceitaRoute
  '/_authenticated/indicadores-trimestre': typeof AuthenticatedIndicadoresTrimestreRoute
  '/_authenticated/meus-royalties': typeof AuthenticatedMeusRoyaltiesRoute
  '/_authenticated/nps': typeof AuthenticatedNpsRoute
  '/_authenticated/operacao': typeof AuthenticatedOperacaoRoute
  '/_authenticated/pagamentos-unidades': typeof AuthenticatedPagamentosUnidadesRoute
  '/_authenticated/painel-cs': typeof AuthenticatedPainelCsRoute
  '/_authenticated/painel-unidade': typeof AuthenticatedPainelUnidadeRoute
  '/_authenticated/reconciliacao': typeof AuthenticatedReconciliacaoRoute
  '/_authenticated/rede': typeof AuthenticatedRedeRoute
  '/_authenticated/rede-headcount': typeof AuthenticatedRedeHeadcountRoute
  '/_authenticated/rede-ltv': typeof AuthenticatedRedeLtvRoute
  '/_authenticated/rede-overview': typeof AuthenticatedRedeOverviewRoute
  '/_authenticated/rede-realizado': typeof AuthenticatedRedeRealizadoRoute
  '/_authenticated/reforma-tributaria': typeof AuthenticatedReformaTributariaRoute
  '/_authenticated/royalties': typeof AuthenticatedRoyaltiesRouteWithChildren
  '/_authenticated/simulador-caixa': typeof AuthenticatedSimuladorCaixaRoute
  '/_authenticated/unidades': typeof AuthenticatedUnidadesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/integracoes': typeof AuthenticatedAdminIntegracoesRoute
  '/_authenticated/admin/perfis': typeof AuthenticatedAdminPerfisRoute
  '/_authenticated/admin/permissoes': typeof AuthenticatedAdminPermissoesRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/admin/validacao': typeof AuthenticatedAdminValidacaoRoute
  '/_authenticated/broker/admin': typeof AuthenticatedBrokerAdminRoute
  '/_authenticated/broker/': typeof AuthenticatedBrokerIndexRoute
  '/_authenticated/royalties/': typeof AuthenticatedRoyaltiesIndexRoute
  '/_authenticated/royalties/$unidadeId/$mes': typeof AuthenticatedRoyaltiesUnidadeIdMesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/redefinir-senha'
    | '/trust'
    | '/atividade'
    | '/auditoria'
    | '/auditoria-faturamento'
    | '/auditoria-interna'
    | '/base-contatos'
    | '/bi-vendas'
    | '/clientes'
    | '/comissoes'
    | '/contas-receber'
    | '/despesas-cm'
    | '/disparos-whatsapp'
    | '/dre-partners'
    | '/ebit-operacional'
    | '/fila-cella'
    | '/financeiro-partners'
    | '/funil-receita'
    | '/indicadores-trimestre'
    | '/meus-royalties'
    | '/nps'
    | '/operacao'
    | '/pagamentos-unidades'
    | '/painel-cs'
    | '/painel-unidade'
    | '/reconciliacao'
    | '/rede'
    | '/rede-headcount'
    | '/rede-ltv'
    | '/rede-overview'
    | '/rede-realizado'
    | '/reforma-tributaria'
    | '/royalties'
    | '/simulador-caixa'
    | '/unidades'
    | '/admin/integracoes'
    | '/admin/perfis'
    | '/admin/permissoes'
    | '/admin/usuarios'
    | '/admin/validacao'
    | '/broker/admin'
    | '/broker/'
    | '/royalties/'
    | '/royalties/$unidadeId/$mes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/redefinir-senha'
    | '/trust'
    | '/atividade'
    | '/auditoria'
    | '/auditoria-faturamento'
    | '/auditoria-interna'
    | '/base-contatos'
    | '/bi-vendas'
    | '/clientes'
    | '/comissoes'
    | '/contas-receber'
    | '/despesas-cm'
    | '/disparos-whatsapp'
    | '/dre-partners'
    | '/ebit-operacional'
    | '/fila-cella'
    | '/financeiro-partners'
    | '/funil-receita'
    | '/indicadores-trimestre'
    | '/meus-royalties'
    | '/nps'
    | '/operacao'
    | '/pagamentos-unidades'
    | '/painel-cs'
    | '/painel-unidade'
    | '/reconciliacao'
    | '/rede'
    | '/rede-headcount'
    | '/rede-ltv'
    | '/rede-overview'
    | '/rede-realizado'
    | '/reforma-tributaria'
    | '/simulador-caixa'
    | '/unidades'
    | '/'
    | '/admin/integracoes'
    | '/admin/perfis'
    | '/admin/permissoes'
    | '/admin/usuarios'
    | '/admin/validacao'
    | '/broker/admin'
    | '/broker'
    | '/royalties'
    | '/royalties/$unidadeId/$mes'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/redefinir-senha'
    | '/trust'
    | '/_authenticated/atividade'
    | '/_authenticated/auditoria'
    | '/_authenticated/auditoria-faturamento'
    | '/_authenticated/auditoria-interna'
    | '/_authenticated/base-contatos'
    | '/_authenticated/bi-vendas'
    | '/_authenticated/clientes'
    | '/_authenticated/comissoes'
    | '/_authenticated/contas-receber'
    | '/_authenticated/despesas-cm'
    | '/_authenticated/disparos-whatsapp'
    | '/_authenticated/dre-partners'
    | '/_authenticated/ebit-operacional'
    | '/_authenticated/fila-cella'
    | '/_authenticated/financeiro-partners'
    | '/_authenticated/funil-receita'
    | '/_authenticated/indicadores-trimestre'
    | '/_authenticated/meus-royalties'
    | '/_authenticated/nps'
    | '/_authenticated/operacao'
    | '/_authenticated/pagamentos-unidades'
    | '/_authenticated/painel-cs'
    | '/_authenticated/painel-unidade'
    | '/_authenticated/reconciliacao'
    | '/_authenticated/rede'
    | '/_authenticated/rede-headcount'
    | '/_authenticated/rede-ltv'
    | '/_authenticated/rede-overview'
    | '/_authenticated/rede-realizado'
    | '/_authenticated/reforma-tributaria'
    | '/_authenticated/royalties'
    | '/_authenticated/simulador-caixa'
    | '/_authenticated/unidades'
    | '/_authenticated/'
    | '/_authenticated/admin/integracoes'
    | '/_authenticated/admin/perfis'
    | '/_authenticated/admin/permissoes'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/admin/validacao'
    | '/_authenticated/broker/admin'
    | '/_authenticated/broker/'
    | '/_authenticated/royalties/'
    | '/_authenticated/royalties/$unidadeId/$mes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  TrustRoute: typeof TrustRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/unidades': {
      id: '/_authenticated/unidades'
      path: '/unidades'
      fullPath: '/unidades'
      preLoaderRoute: typeof AuthenticatedUnidadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/simulador-caixa': {
      id: '/_authenticated/simulador-caixa'
      path: '/simulador-caixa'
      fullPath: '/simulador-caixa'
      preLoaderRoute: typeof AuthenticatedSimuladorCaixaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/royalties': {
      id: '/_authenticated/royalties'
      path: '/royalties'
      fullPath: '/royalties'
      preLoaderRoute: typeof AuthenticatedRoyaltiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reforma-tributaria': {
      id: '/_authenticated/reforma-tributaria'
      path: '/reforma-tributaria'
      fullPath: '/reforma-tributaria'
      preLoaderRoute: typeof AuthenticatedReformaTributariaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rede-realizado': {
      id: '/_authenticated/rede-realizado'
      path: '/rede-realizado'
      fullPath: '/rede-realizado'
      preLoaderRoute: typeof AuthenticatedRedeRealizadoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rede-overview': {
      id: '/_authenticated/rede-overview'
      path: '/rede-overview'
      fullPath: '/rede-overview'
      preLoaderRoute: typeof AuthenticatedRedeOverviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rede-ltv': {
      id: '/_authenticated/rede-ltv'
      path: '/rede-ltv'
      fullPath: '/rede-ltv'
      preLoaderRoute: typeof AuthenticatedRedeLtvRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rede-headcount': {
      id: '/_authenticated/rede-headcount'
      path: '/rede-headcount'
      fullPath: '/rede-headcount'
      preLoaderRoute: typeof AuthenticatedRedeHeadcountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rede': {
      id: '/_authenticated/rede'
      path: '/rede'
      fullPath: '/rede'
      preLoaderRoute: typeof AuthenticatedRedeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reconciliacao': {
      id: '/_authenticated/reconciliacao'
      path: '/reconciliacao'
      fullPath: '/reconciliacao'
      preLoaderRoute: typeof AuthenticatedReconciliacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel-unidade': {
      id: '/_authenticated/painel-unidade'
      path: '/painel-unidade'
      fullPath: '/painel-unidade'
      preLoaderRoute: typeof AuthenticatedPainelUnidadeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel-cs': {
      id: '/_authenticated/painel-cs'
      path: '/painel-cs'
      fullPath: '/painel-cs'
      preLoaderRoute: typeof AuthenticatedPainelCsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pagamentos-unidades': {
      id: '/_authenticated/pagamentos-unidades'
      path: '/pagamentos-unidades'
      fullPath: '/pagamentos-unidades'
      preLoaderRoute: typeof AuthenticatedPagamentosUnidadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operacao': {
      id: '/_authenticated/operacao'
      path: '/operacao'
      fullPath: '/operacao'
      preLoaderRoute: typeof AuthenticatedOperacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nps': {
      id: '/_authenticated/nps'
      path: '/nps'
      fullPath: '/nps'
      preLoaderRoute: typeof AuthenticatedNpsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meus-royalties': {
      id: '/_authenticated/meus-royalties'
      path: '/meus-royalties'
      fullPath: '/meus-royalties'
      preLoaderRoute: typeof AuthenticatedMeusRoyaltiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/indicadores-trimestre': {
      id: '/_authenticated/indicadores-trimestre'
      path: '/indicadores-trimestre'
      fullPath: '/indicadores-trimestre'
      preLoaderRoute: typeof AuthenticatedIndicadoresTrimestreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/funil-receita': {
      id: '/_authenticated/funil-receita'
      path: '/funil-receita'
      fullPath: '/funil-receita'
      preLoaderRoute: typeof AuthenticatedFunilReceitaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro-partners': {
      id: '/_authenticated/financeiro-partners'
      path: '/financeiro-partners'
      fullPath: '/financeiro-partners'
      preLoaderRoute: typeof AuthenticatedFinanceiroPartnersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fila-cella': {
      id: '/_authenticated/fila-cella'
      path: '/fila-cella'
      fullPath: '/fila-cella'
      preLoaderRoute: typeof AuthenticatedFilaCellaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ebit-operacional': {
      id: '/_authenticated/ebit-operacional'
      path: '/ebit-operacional'
      fullPath: '/ebit-operacional'
      preLoaderRoute: typeof AuthenticatedEbitOperacionalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dre-partners': {
      id: '/_authenticated/dre-partners'
      path: '/dre-partners'
      fullPath: '/dre-partners'
      preLoaderRoute: typeof AuthenticatedDrePartnersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/disparos-whatsapp': {
      id: '/_authenticated/disparos-whatsapp'
      path: '/disparos-whatsapp'
      fullPath: '/disparos-whatsapp'
      preLoaderRoute: typeof AuthenticatedDisparosWhatsappRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/despesas-cm': {
      id: '/_authenticated/despesas-cm'
      path: '/despesas-cm'
      fullPath: '/despesas-cm'
      preLoaderRoute: typeof AuthenticatedDespesasCmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contas-receber': {
      id: '/_authenticated/contas-receber'
      path: '/contas-receber'
      fullPath: '/contas-receber'
      preLoaderRoute: typeof AuthenticatedContasReceberRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comissoes': {
      id: '/_authenticated/comissoes'
      path: '/comissoes'
      fullPath: '/comissoes'
      preLoaderRoute: typeof AuthenticatedComissoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bi-vendas': {
      id: '/_authenticated/bi-vendas'
      path: '/bi-vendas'
      fullPath: '/bi-vendas'
      preLoaderRoute: typeof AuthenticatedBiVendasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/base-contatos': {
      id: '/_authenticated/base-contatos'
      path: '/base-contatos'
      fullPath: '/base-contatos'
      preLoaderRoute: typeof AuthenticatedBaseContatosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auditoria-interna': {
      id: '/_authenticated/auditoria-interna'
      path: '/auditoria-interna'
      fullPath: '/auditoria-interna'
      preLoaderRoute: typeof AuthenticatedAuditoriaInternaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auditoria-faturamento': {
      id: '/_authenticated/auditoria-faturamento'
      path: '/auditoria-faturamento'
      fullPath: '/auditoria-faturamento'
      preLoaderRoute: typeof AuthenticatedAuditoriaFaturamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auditoria': {
      id: '/_authenticated/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuthenticatedAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atividade': {
      id: '/_authenticated/atividade'
      path: '/atividade'
      fullPath: '/atividade'
      preLoaderRoute: typeof AuthenticatedAtividadeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/royalties/': {
      id: '/_authenticated/royalties/'
      path: '/'
      fullPath: '/royalties/'
      preLoaderRoute: typeof AuthenticatedRoyaltiesIndexRouteImport
      parentRoute: typeof AuthenticatedRoyaltiesRoute
    }
    '/_authenticated/broker/': {
      id: '/_authenticated/broker/'
      path: '/broker'
      fullPath: '/broker/'
      preLoaderRoute: typeof AuthenticatedBrokerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/broker/admin': {
      id: '/_authenticated/broker/admin'
      path: '/broker/admin'
      fullPath: '/broker/admin'
      preLoaderRoute: typeof AuthenticatedBrokerAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/validacao': {
      id: '/_authenticated/admin/validacao'
      path: '/admin/validacao'
      fullPath: '/admin/validacao'
      preLoaderRoute: typeof AuthenticatedAdminValidacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/permissoes': {
      id: '/_authenticated/admin/permissoes'
      path: '/admin/permissoes'
      fullPath: '/admin/permissoes'
      preLoaderRoute: typeof AuthenticatedAdminPermissoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/perfis': {
      id: '/_authenticated/admin/perfis'
      path: '/admin/perfis'
      fullPath: '/admin/perfis'
      preLoaderRoute: typeof AuthenticatedAdminPerfisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/integracoes': {
      id: '/_authenticated/admin/integracoes'
      path: '/admin/integracoes'
      fullPath: '/admin/integracoes'
      preLoaderRoute: typeof AuthenticatedAdminIntegracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/royalties/$unidadeId/$mes': {
      id: '/_authenticated/royalties/$unidadeId/$mes'
      path: '/$unidadeId/$mes'
      fullPath: '/royalties/$unidadeId/$mes'
      preLoaderRoute: typeof AuthenticatedRoyaltiesUnidadeIdMesRouteImport
      parentRoute: typeof AuthenticatedRoyaltiesRoute
    }
  }
}

interface AuthenticatedRoyaltiesRouteChildren {
  AuthenticatedRoyaltiesIndexRoute: typeof AuthenticatedRoyaltiesIndexRoute
  AuthenticatedRoyaltiesUnidadeIdMesRoute: typeof AuthenticatedRoyaltiesUnidadeIdMesRoute
}

const AuthenticatedRoyaltiesRouteChildren: AuthenticatedRoyaltiesRouteChildren =
  {
    AuthenticatedRoyaltiesIndexRoute: AuthenticatedRoyaltiesIndexRoute,
    AuthenticatedRoyaltiesUnidadeIdMesRoute:
      AuthenticatedRoyaltiesUnidadeIdMesRoute,
  }

const AuthenticatedRoyaltiesRouteWithChildren =
  AuthenticatedRoyaltiesRoute._addFileChildren(
    AuthenticatedRoyaltiesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAtividadeRoute: typeof AuthenticatedAtividadeRoute
  AuthenticatedAuditoriaRoute: typeof AuthenticatedAuditoriaRoute
  AuthenticatedAuditoriaFaturamentoRoute: typeof AuthenticatedAuditoriaFaturamentoRoute
  AuthenticatedAuditoriaInternaRoute: typeof AuthenticatedAuditoriaInternaRoute
  AuthenticatedBaseContatosRoute: typeof AuthenticatedBaseContatosRoute
  AuthenticatedBiVendasRoute: typeof AuthenticatedBiVendasRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedComissoesRoute: typeof AuthenticatedComissoesRoute
  AuthenticatedContasReceberRoute: typeof AuthenticatedContasReceberRoute
  AuthenticatedDespesasCmRoute: typeof AuthenticatedDespesasCmRoute
  AuthenticatedDisparosWhatsappRoute: typeof AuthenticatedDisparosWhatsappRoute
  AuthenticatedDrePartnersRoute: typeof AuthenticatedDrePartnersRoute
  AuthenticatedEbitOperacionalRoute: typeof AuthenticatedEbitOperacionalRoute
  AuthenticatedFilaCellaRoute: typeof AuthenticatedFilaCellaRoute
  AuthenticatedFinanceiroPartnersRoute: typeof AuthenticatedFinanceiroPartnersRoute
  AuthenticatedFunilReceitaRoute: typeof AuthenticatedFunilReceitaRoute
  AuthenticatedIndicadoresTrimestreRoute: typeof AuthenticatedIndicadoresTrimestreRoute
  AuthenticatedMeusRoyaltiesRoute: typeof AuthenticatedMeusRoyaltiesRoute
  AuthenticatedNpsRoute: typeof AuthenticatedNpsRoute
  AuthenticatedOperacaoRoute: typeof AuthenticatedOperacaoRoute
  AuthenticatedPagamentosUnidadesRoute: typeof AuthenticatedPagamentosUnidadesRoute
  AuthenticatedPainelCsRoute: typeof AuthenticatedPainelCsRoute
  AuthenticatedPainelUnidadeRoute: typeof AuthenticatedPainelUnidadeRoute
  AuthenticatedReconciliacaoRoute: typeof AuthenticatedReconciliacaoRoute
  AuthenticatedRedeRoute: typeof AuthenticatedRedeRoute
  AuthenticatedRedeHeadcountRoute: typeof AuthenticatedRedeHeadcountRoute
  AuthenticatedRedeLtvRoute: typeof AuthenticatedRedeLtvRoute
  AuthenticatedRedeOverviewRoute: typeof AuthenticatedRedeOverviewRoute
  AuthenticatedRedeRealizadoRoute: typeof AuthenticatedRedeRealizadoRoute
  AuthenticatedReformaTributariaRoute: typeof AuthenticatedReformaTributariaRoute
  AuthenticatedRoyaltiesRoute: typeof AuthenticatedRoyaltiesRouteWithChildren
  AuthenticatedSimuladorCaixaRoute: typeof AuthenticatedSimuladorCaixaRoute
  AuthenticatedUnidadesRoute: typeof AuthenticatedUnidadesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminIntegracoesRoute: typeof AuthenticatedAdminIntegracoesRoute
  AuthenticatedAdminPerfisRoute: typeof AuthenticatedAdminPerfisRoute
  AuthenticatedAdminPermissoesRoute: typeof AuthenticatedAdminPermissoesRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminValidacaoRoute: typeof AuthenticatedAdminValidacaoRoute
  AuthenticatedBrokerAdminRoute: typeof AuthenticatedBrokerAdminRoute
  AuthenticatedBrokerIndexRoute: typeof AuthenticatedBrokerIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAtividadeRoute: AuthenticatedAtividadeRoute,
  AuthenticatedAuditoriaRoute: AuthenticatedAuditoriaRoute,
  AuthenticatedAuditoriaFaturamentoRoute:
    AuthenticatedAuditoriaFaturamentoRoute,
  AuthenticatedAuditoriaInternaRoute: AuthenticatedAuditoriaInternaRoute,
  AuthenticatedBaseContatosRoute: AuthenticatedBaseContatosRoute,
  AuthenticatedBiVendasRoute: AuthenticatedBiVendasRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedComissoesRoute: AuthenticatedComissoesRoute,
  AuthenticatedContasReceberRoute: AuthenticatedContasReceberRoute,
  AuthenticatedDespesasCmRoute: AuthenticatedDespesasCmRoute,
  AuthenticatedDisparosWhatsappRoute: AuthenticatedDisparosWhatsappRoute,
  AuthenticatedDrePartnersRoute: AuthenticatedDrePartnersRoute,
  AuthenticatedEbitOperacionalRoute: AuthenticatedEbitOperacionalRoute,
  AuthenticatedFilaCellaRoute: AuthenticatedFilaCellaRoute,
  AuthenticatedFinanceiroPartnersRoute: AuthenticatedFinanceiroPartnersRoute,
  AuthenticatedFunilReceitaRoute: AuthenticatedFunilReceitaRoute,
  AuthenticatedIndicadoresTrimestreRoute:
    AuthenticatedIndicadoresTrimestreRoute,
  AuthenticatedMeusRoyaltiesRoute: AuthenticatedMeusRoyaltiesRoute,
  AuthenticatedNpsRoute: AuthenticatedNpsRoute,
  AuthenticatedOperacaoRoute: AuthenticatedOperacaoRoute,
  AuthenticatedPagamentosUnidadesRoute: AuthenticatedPagamentosUnidadesRoute,
  AuthenticatedPainelCsRoute: AuthenticatedPainelCsRoute,
  AuthenticatedPainelUnidadeRoute: AuthenticatedPainelUnidadeRoute,
  AuthenticatedReconciliacaoRoute: AuthenticatedReconciliacaoRoute,
  AuthenticatedRedeRoute: AuthenticatedRedeRoute,
  AuthenticatedRedeHeadcountRoute: AuthenticatedRedeHeadcountRoute,
  AuthenticatedRedeLtvRoute: AuthenticatedRedeLtvRoute,
  AuthenticatedRedeOverviewRoute: AuthenticatedRedeOverviewRoute,
  AuthenticatedRedeRealizadoRoute: AuthenticatedRedeRealizadoRoute,
  AuthenticatedReformaTributariaRoute: AuthenticatedReformaTributariaRoute,
  AuthenticatedRoyaltiesRoute: AuthenticatedRoyaltiesRouteWithChildren,
  AuthenticatedSimuladorCaixaRoute: AuthenticatedSimuladorCaixaRoute,
  AuthenticatedUnidadesRoute: AuthenticatedUnidadesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminIntegracoesRoute: AuthenticatedAdminIntegracoesRoute,
  AuthenticatedAdminPerfisRoute: AuthenticatedAdminPerfisRoute,
  AuthenticatedAdminPermissoesRoute: AuthenticatedAdminPermissoesRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAdminValidacaoRoute: AuthenticatedAdminValidacaoRoute,
  AuthenticatedBrokerAdminRoute: AuthenticatedBrokerAdminRoute,
  AuthenticatedBrokerIndexRoute: AuthenticatedBrokerIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  TrustRoute: TrustRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
