// This file is automatically generated. Do not edit it directly.
//
// ⚠️ EDITADO À MÃO (24/08/2026): a sessão foi movida de localStorage para
// cookie no domínio raiz (.planningbrain.com.br), para que ops e growth
// compartilhem o login. Ver cookie-storage.ts e PLANO-SSO-OPS-GROWTH.md.
// Este arquivo nasceu gerado automaticamente: se algum gerador o reescrever,
// a linha `storage: cookieStorage` abaixo se perde e o login volta a ser
// isolado por subdomínio — reaplicar.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { cookieStorage } from './cookie-storage';
import { opcoesDeSchema } from './schema';

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Set them in the Vercel project settings.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? cookieStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
      // Na recuperação, nem o SDK nem um scanner devem consumir o link antes
      // de a pessoa salvar a senha. O formulário trata os links legados também.
      detectSessionInUrl: typeof window === 'undefined' || window.location.pathname !== '/redefinir-senha',

    },
    // Ver schema.ts: sem a variável de ambiente isto é um objeto vazio e nada
    // muda. Com ela, todo `.from()` e `.rpc()` passa a falar com o schema do
    // produto no banco único.
    ...opcoesDeSchema,
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

